"""Initial migration.

Revision ID: 627d4d4d458e
Revises: 
Create Date: 2022-07-26 21:22:10.998922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627d4d4d458e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todo SET completed=FALSE WHERE completed IS NULL')

    op.alter_column('todo','completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
