"""empty message

Revision ID: d7e1760745f0
Revises: 627d4d4d458e
Create Date: 2022-08-02 09:57:58.079881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e1760745f0'
down_revision = '627d4d4d458e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade(): 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
